### ISSUE TITLE
"The first time you login you need to install the SDK."

### ISSUE THREAD

**Issue by MacDada** [matthew-james/esp-vagrant#1]
Well, that's what provisioners are for ;-)

_BTW, this project is a great idea!_

**Comment by matthew-james** [comment]
Installing on provision fails for me.  I haven't dug into the issue to figure out why yet.

It just needs a separate script that runs as ````privileged: false````, since the sdk wont run as root, so if someone can figure out the issue it should be simple to do.

I also tried installing the sdk and repacking into a new base box for atlas, but the base box is pretty huge so I'm not sure if that's worth doing.  This would eliminate the lengthy provision time, but I would need to automate the box packing for every SDK update, because it is time consuming and not that much fun :)
